name: Tests

on: ['push']

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies Frontend
        run: yarn install
        working-directory: frontend

      - name: Run Tests
        run: yarn test
        working-directory: frontend

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: frontend/coverage
